### ISSUE TITLE
Error: braintree is not defined

### ISSUE THREAD

**Issue by turbogeek** [patrickml/braintree#20]
Hi, maybe this is just a documentation issue, but I am getting a Error: braintree is not defined. Do I need to install Braintree? It is not clear if that is my issue or perhaps there is something else going on. Here is the code (keys removed) and the error:
var customer;
try{
    var bt = BrainTreeConnect({

```
    environment:  braintree.Environment.Sandbox,
    merchantId:   '...',
    publicKey:    '...',
    privateKey:   '...'
});
customer = bt.customer.create(config);
console.log("customer:",customer);
```

} catch(error){
    throw new Meteor.Error(1001, error.message);
}

W20150913-23:13:01.481(-5)? (STDERR) Error: braintree is not defined [1001]
W20150913-23:13:01.481(-5)? (STDERR)     at app/server/braintree.js:21:11
W20150913-23:13:01.481(-5)? (STDERR)     at app/server/braintree.js:24:3
W20150913-23:13:01.481(-5)? (STDERR)     at /Users/turbogeek/work/q_again/quantum/.meteor/local/build/programs/server/boot.js:222:10
W20150913-23:13:01.481(-5)? (STDERR)     at Array.forEach (native)
W20150913-23:13:01.481(-5)? (STDERR)     at Function._.each._.forEach (/Users/turbogeek/.meteor/packages/meteor-tool/.1.1.3.96aw17++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150913-23:13:01.481(-5)? (STDERR)     at /Users/turbogeek/work/q_again/quantum/.meteor/local/build/programs/server/boot.js:117:5

**Comment by patrickml** [comment]
I believe `braintree` needs to be `Braintree`

**Comment by turbogeek** [comment]
Ok, Braintree/braintree was the issue. Here is a version of the example with a sample config for creating the customer (got it from the Braintree site). From long experience I have learned that the only good sample code is executable sample code :o)

```
var customer;
try{
    var bt = BrainTreeConnect({
        //If you set an ENV variable for PRODUCTION you can dynamically change out sandbox and production
        environment:  Braintree.Environment.Sandbox,
        merchantId:   '...',
        publicKey:    '...',
        privateKey:   '...'
    });
    var config ={
        firstName: "Jen",
        lastName: "Smith",
        company: "Braintree",
        email: "jen@example.com",
        phone: "312.555.1234",
        fax: "614.555.5678",
        website: "www.example.com"
    };

    customer = bt.customer.create(config, function (err, result) {
        console.log( "result.success:", result.success);
        // true
        console.log( "result.customer.id:",result.customer.id);
        // e.g. 494019
    });
    console.log("customer:",customer);
} catch(error){
    throw new Meteor.Error(1001, error.message);
}
```

**Comment by patrickml** [comment]
@turbogeek i agree. i'll update the docs with something similar to your example thank you!
