### ISSUE TITLE
Does this run with Cordova?

### ISSUE THREAD

**Issue by Obiwarn** [patrickml/braintree#24]
I had problems displaying the PayPal Button with the regular JS client API.

**Comment by patrickml** [comment]
I havent used the regular JS client API much so im not 100% sure but i don't see any reason why it wouldnt work on Cordova. Are there any errors in your error log in the cordova browser?

**Comment by Obiwarn** [comment]
It says "unsupported protocol" when I run braintree.setup.

I guess it is because insead of https://mypage.com it now is http://meteor.local.
Which the client probably thinks is unsecure (non https).
