### ISSUE TITLE
Meteor 1.3

### ISSUE THREAD

**Issue by d4nyll** [patrickml/braintree#26]
Thank you for taking the time to wrap the braintree library. But now that you can use the [npm package](https://www.npmjs.com/package/braintree) directly, you should put a note in the `README.md` to advice  new users to use the npm package directly.

**Comment by wjfieseler** [comment]
@d4nyll 

How would I go about using the npm package directly?

**Comment by patrickml** [comment]
@wjfieseler you should be able to import this from npm like so

`npm install --save braintree`

Then in your code do something like

```
import Braintree from 'braintree';

const bt = Braintree.connect(Meteor.settings.braintree.token);

bt.customer.create(); // do stuff
```

**Comment by patrickml** [comment]
Thanks @d4nyll I just did
