### ISSUE TITLE
Do we also need the client SDK along with this package?

### ISSUE THREAD

**Issue by niranjans** [patrickml/braintree#4]
I am a little confused looking at the Braintree documentation and matching it with this package. According to Braintree, we need a client SDK and server SDK for the payment features. Also not sure how to get the `nonceFromTheClient`.

 Does this package include both? If not, do you recommend any client package with this? 

Thanks

**Comment by patrickml** [comment]
Hey Niranjan,

Great question, I will update the docs to explain that you can simply add
the '<script src="https://js.braintreegateway.com/v2/braintree.js"></script>
<script>' to your 'head.html' file to import the code with out the extra
overhead of a package for it. If anyone else says that it would make their
lives easier Ill add it to the package. I left it out so it was up to the
user if they wanted it in case the didn't need it.

**Comment by niranjans** [comment]
Got it. That makes sense. Thanks for your response and for the package.
